# The URL the site will be built for
base_url = "https://vim.tips"
theme = "slim"

build_search_index = true
compile_sass = true
highlight_code = true

title = "vim.tips"
description = ""
generate_feed = true

taxonomies = [
    {name = "tags", rss = true},
]

[extra]
slim_summary = false
slim_content = false
slim_menu = [
    {url = "$BASE_URL/about/", name = "About"},
    {url = "$BASE_URL/tags", name = "Tags"}
]
slim_social = [
    {url = "https://github.com/vim-tips", name = "Github"}
]
