# The URL the site will be built for
base_url = "https://vim.tips"
theme = "slim"

compile_sass = true
build_search_index = true

title = "vim.tips"
description = "vim tips"
generate_feed = true

taxonomies = [
    {name = "tags", paginate_by = 5, rss = true}
]

[extra]
slim_summary = false
slim_content = false
slim_netlify_identity = false
slim_menu = [
    {url = "$BASE_URL/tags", name = "Tags"}
]
slim_social = [
    {url = "https://github.com/vim-tips/", name = "Github"}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
