name: build

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
  build:
    name: build zola
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
